### ISSUE TITLE
DIALS 2.0 prep work

### ISSUE THREAD

**Issue by Anthchirp** [dials/dials#713]
* [x] branch 1.13 as reference point only
* [x] apply reduced release commit on 1.13
* [x] move 1.13 branch point to correct location and tag
* [x] branch 1.14 as release branch
* [x] blacken the 1.14 branch with isort-equivalent
* [ ] test 1.14 branch
* [ ] then apply the usual release commit and tag on 1.14.

On the main branches expect this to happen
* [x] pull request #686 to be squashed into dials/master
* [x] tag dials/master with v2-dev
* [x] pull request #698 to be merged into dials/master. This will involve some manual work to sort out conflicts
* [x] blacken the post-merge dials master branch as early as possible with isort-equivalent
* [x] pull request cctbx/cctbx_project#292 to be merged into cctbx/master
* [x] blacken dxtbx on master with isort-equivalent
* [x] tag xia2 v0.6.0
* [x] pull request xia2/xia2#253 to be rebased into xia2/master
* [x] blacken xia2 on master with isort-equivalent
* [ ] then sort out any tests failing as result of the merge

Further
* [ ] Split single Jenkins job into build+test and build+regression for linux and mac to make it easier to keep the 1.14 branch around for longer that usual.

**Comment by Anthchirp** [comment]
Pre-merge warning:
I would advise all DIALS developers to get any unmerged work into master before we merge the DIALS 2.0 branch. If you don't know whether you have unmerged work I would suggest running
```git remote prune origin```
to remove stale tags, then ```git branch``` or ```gitk --simplify-by-decoration --all``` to view all branches you have in your repository and then look into any potential candidate branches as necessary.

When we merge DIALS 2.0 chances are that none of your patches will apply cleanly and you will have a lot of conflict resolving on your hand. A likely target for this work is Thursday, that would give you roughly 72 hours.

**Comment by Anthchirp** [comment]
likely worth running black together with isort post-merge and on the release branch.

**Comment by Anthchirp** [comment]
sent mail to dials-support: 
> Please do not commit/push to dials, xia2, cctbx (dxtbx directory only, anywhere else is fine)
> from 13:30 GMT (05:30 PST) tomorrow until the work in issue 713 is completed.
> I expect this to take less than 2 hours.

**Comment by Anthchirp** [comment]
sorting import breaks things, so left this out for now.

**Comment by Anthchirp** [comment]
Work completed. 2 tests failing due to datablock changes. These will be picked up in due course. 1.14 release bits can be dealt with independently.

**Comment by Anthchirp** [comment]
all tests pass now \o/

**Comment by Anthchirp** [comment]
remaining tasks => #649
